version: "3"
services:
  redis:
    container_name: redis
    image: redis:6
    restart: always
    ports:
      - 6379:6379
  postgres:
    container_name: postgres
    image: postgres:13.3-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: banking_app_v2
  postgres-adminer:
    container_name: postgres-adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080
